%% motion model

function m = motionModel(x, delta_real)

    m = [...
         x(1) + delta_real(1) * cosd(x(3) + delta_real(2)),...
         x(2) + delta_real(1) * sind(x(3) + delta_real(2)),...
         x(3) + delta_real(2)...
         ];
     
end